### ISSUE TITLE
Crashes when closing the Theme form.

### ISSUE THREAD

**Issue by HadManySons** [Jukari2003/Bullet-Blender#1]
Windows 10 1903. HP EliteBook 745 G6

Crashes whenever I close the theme form. ISE restarts itself though. No error in the console, because ISE crashes as well.

**Comment by Jukari2003** [comment]
I am unable to replicate your issue on my computer. 

However, I made a minor change to the code that might eliminate this problem. Please download Version 1.2 and see if it fixes the error.

If not:
Can you walk me through exactly how you're opening/closing the window? Does it prompt you to save settings before you close?

**Comment by HadManySons** [comment]
Looks like version 1.2 seemed to fix whatever the issue was. I was able to make changes and save them.
